"""add_user_id_to_runtime_settings

Revision ID: 999667e663d0
Revises: 3cd0f4ac9318
Create Date: 2026-06-16 21:52:14.792659

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '999667e663d0'
down_revision = '3cd0f4ac9318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    # Drop existing primary key constraint
    op.drop_constraint('app_runtime_settings_pkey', 'app_runtime_settings', type_='primary')
    
    # Add id column as nullable first
    op.add_column('app_runtime_settings', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('app_runtime_settings', sa.Column('user_id', sa.Uuid(), nullable=True))
    
    # Populate id with sequential values
    op.execute("""
        UPDATE app_runtime_settings 
        SET id = subq.new_id 
        FROM (SELECT key, ROW_NUMBER() OVER (ORDER BY key) as new_id FROM app_runtime_settings) subq
        WHERE app_runtime_settings.key = subq.key
    """)
    
    # Populate user_id with a default user (first user in the system)
    op.execute("""
        UPDATE app_runtime_settings 
        SET user_id = (SELECT id FROM users LIMIT 1)
        WHERE user_id IS NULL
    """)
    
    # Now make columns NOT NULL
    op.alter_column('app_runtime_settings', 'id', nullable=False)
    op.alter_column('app_runtime_settings', 'user_id', nullable=False)
    
    # Create primary key on id
    op.create_primary_key('pk_app_runtime_settings', 'app_runtime_settings', ['id'])
    
    op.alter_column('app_runtime_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_runtime_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint('uq_runtime_settings_key_user', 'app_runtime_settings', ['key', 'user_id'])
    op.create_foreign_key('fk_app_runtime_settings_user_id__users', 'app_runtime_settings', 'users', ['user_id'], ['id'])
    op.alter_column('execution_monitoring_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_monitoring_snapshots', 'last_refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('load_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('load_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('monitoring_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('smart_comms_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('smart_comms_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('smart_comms_conversations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('smart_comms_conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('monitoring_alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('load_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('load_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_monitoring_snapshots', 'last_refreshed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('execution_monitoring_snapshots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('fk_app_runtime_settings_user_id__users', 'app_runtime_settings', type_='foreignkey')
    op.drop_constraint('uq_runtime_settings_key_user', 'app_runtime_settings', type_='unique')
    op.alter_column('app_runtime_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_runtime_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('pk_app_runtime_settings', 'app_runtime_settings', type_='primary')
    op.drop_column('app_runtime_settings', 'user_id')
    op.drop_column('app_runtime_settings', 'id')
    op.create_primary_key('app_runtime_settings_pkey', 'app_runtime_settings', ['key'])
    op.alter_column('agent_activities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
