"""Monitoring alert for operational risk visibility."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Enum, ForeignKey, JSON, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.backend.core.domain_enums import (
    MonitoringAlertSeverity,
    MonitoringAlertStatus,
    MonitoringAlertType,
)
from app.backend.db.base import Base


class MonitoringAlert(Base):
    """Persisted alert generated by the monitoring agent rule engine."""

    __tablename__ = "monitoring_alerts"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    load_order_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("load_orders.id", name="fk_monitoring_alerts_load_order_id__load_orders"),
        nullable=True,
    )
    alert_type: Mapped[MonitoringAlertType] = mapped_column(
        Enum(
            MonitoringAlertType,
            native_enum=False,
            create_constraint=True,
            length=50,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    severity: Mapped[MonitoringAlertSeverity] = mapped_column(
        Enum(
            MonitoringAlertSeverity,
            native_enum=False,
            create_constraint=True,
            length=50,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    status: Mapped[MonitoringAlertStatus] = mapped_column(
        Enum(
            MonitoringAlertStatus,
            native_enum=False,
            create_constraint=True,
            length=50,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    dedupe_key: Mapped[str] = mapped_column(String(255), nullable=False)
    extra_metadata: Mapped[dict[str, object] | None] = mapped_column(
        "metadata", JSON, nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.current_timestamp(),
        nullable=False,
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(), nullable=True)
